# Generated by Django 4.2.6 on 2023-10-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disponivel', models.BooleanField(default=True)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
